# Generated by Django 2.1.10 on 2019-07-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='DesCrip',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='pic',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
