# Generated by Django 2.1.10 on 2019-07-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0004_auto_20190703_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pic',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
