# Generated by Django 2.1.10 on 2019-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0007_auto_20190704_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='MainMenuType',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='MainMenuType',
            field=models.ManyToManyField(to='restobar.Menu'),
        ),
    ]
