# Generated by Django 2.1.10 on 2019-07-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0009_auto_20190708_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='MainMenuType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restobar.Menu'),
        ),
    ]
