# Generated by Django 2.1.10 on 2019-07-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0010_auto_20190711_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('ContectNo', models.CharField(max_length=200)),
                ('No_Of_person', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('preferred_food', models.IntegerField()),
                ('Occasion', models.CharField(max_length=100)),
            ],
        ),
    ]
