# Generated by Django 2.1.10 on 2019-07-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0011_reservations1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations1',
            new_name='Reservations',
        ),
    ]
