# Generated by Django 2.1.10 on 2019-07-15 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0014_auto_20190713_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
