# Generated by Django 2.1.10 on 2019-07-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0015_auto_20190715_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occasion',
            new_name='Occasion1',
        ),
    ]
