# Generated by Django 2.1.10 on 2019-07-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restobar', '0016_auto_20190717_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occasion1',
            new_name='Occasion',
        ),
    ]
